image_logo_path = './res/image/tbond-oled.png'
image_default_path='./res/image/Black.png'
font_path = './res/font/hanmaumgodic.ttf'
not_connect_path ='./res/image/no_preview.jpg'
preview_img_path ='./res/image/test.jpg'
choice_img_path = './res/image/White.png'

image_audio_level_0 = './res/image/audioLevelMeter/level_0.png'
image_audio_level_1 = './res/image/audioLevelMeter/level_1.png'
image_audio_level_2 = './res/image/audioLevelMeter/level_2.png'
image_audio_level_3 = './res/image/audioLevelMeter/level_3.png'
image_audio_level_4 = './res/image/audioLevelMeter/level_4.png'
image_audio_level_5 = './res/image/audioLevelMeter/level_5.png'
image_audio_level_6 = './res/image/audioLevelMeter/level_6.png'
image_audio_level_7 = './res/image/audioLevelMeter/level_7.png'
image_audio_level_8 = './res/image/audioLevelMeter/level_8.png'
image_audio_level_9 = './res/image/audioLevelMeter/level_9.png'
image_audio_level_10 = './res/image/audioLevelMeter/level_10.png'
image_audio_level_11 = './res/image/audioLevelMeter/level_11.png'
image_audio_level_12 = './res/image/audioLevelMeter/level_12.png'
image_audio_level_13 = './res/image/audioLevelMeter/level_13.png'

image_usb_network_on = './res/image/network/usb_network_on.png'
image_usb_network_off= './res/image/network/usb_network_off.png'
image_lan_network_on = './res/image/network/lan_network_on.png'
image_lan_network_off= './res/image/network/lan_network_off.png'