# Draw Display
SET_DRAW_PREVIEW = 1

SET_LEFT_AUDIO_LEVEL = 2
SET_RIGHT_AUDIO_LEVEL = 3

SET_DRAW_TEXT_CONNECT_TIME = 4


SET_DRAW_TEXT_FIRST = 11
SET_DRAW_TEXT_SECOND = 12
SET_DRAW_TEXT_THIRD = 13
SET_DRAW_TEXT_FOURTH = 14
SET_CHOICE_TEXT_NUMBER = 15
SET_CLEAR_ALL_TEXT = 16

SET_USB_NETWORK_STATE_FIRST = 21
SET_USB_NETWORK_STATE_SECOND = 22
SET_USB_NETWORK_STATE_THIRD = 23
SET_USB_NETWORK_STATE_FOURTH = 24
SET_USB_NETWORK_STATE_FIFTH = 25
SET_LAN_NETWORK_STATE = 26

# BUTTON CONTROL

PRESS_LEFT_BUTTON = 31
PRESS_RIGHT_BUTTON = 32
PRESS_UP_BUTTON = 33
PRESS_DOWN_BUTTON = 34
PRESS_CENTER_BUTTON = 35
PRESS_STREAM_BUTTON = 36